CREATE TABLE asset (asset_id int(10) NOT NULL AUTO_INCREMENT, asset_name int(10), asset_type int(10), asset_type_id int(10) NOT NULL, file_path int(10), dimensions int(10), PRIMARY KEY (asset_id));
CREATE TABLE asset_type (asset_type_id int(10) NOT NULL AUTO_INCREMENT, category_name int(10), description int(10), PRIMARY KEY (asset_type_id));
CREATE TABLE chat (chat_id int(10) NOT NULL AUTO_INCREMENT, user_id int(10) NOT NULL, PRIMARY KEY (chat_id));
CREATE TABLE event (event_id int(10) NOT NULL AUTO_INCREMENT, user_id int(10), event_name varchar(255), event_type_id int(10) NOT NULL, PRIMARY KEY (event_id));
CREATE TABLE event_calendar (calendar_id int(10) NOT NULL AUTO_INCREMENT, event_id int(10) NOT NULL, `date` date, description varchar(255), reminder varchar(255), PRIMARY KEY (calendar_id));
CREATE TABLE event_template (template_id int(10) NOT NULL AUTO_INCREMENT, template_name varchar(255), event_type_id int(10) NOT NULL, description varchar(255), PRIMARY KEY (template_id));
CREATE TABLE event_type (event_type_id int(10) NOT NULL AUTO_INCREMENT, event_type_name varchar(255), PRIMARY KEY (event_type_id));
CREATE TABLE favorite (favorite_id int(10) NOT NULL AUTO_INCREMENT, user_id int(10) NOT NULL, vendor_id int(10) NOT NULL, PRIMARY KEY (favorite_id));
CREATE TABLE message (message_id int(10) NOT NULL AUTO_INCREMENT, chat_id int(10) NOT NULL, text varchar(255), datetime_sent date, PRIMARY KEY (message_id));
CREATE TABLE notification (modification_id int(10) NOT NULL AUTO_INCREMENT, user_id int(10) NOT NULL, content varchar(255), `date` date, status int(10), PRIMARY KEY (modification_id));
CREATE TABLE reservation (reservation_id int(10) NOT NULL AUTO_INCREMENT, user_id int(10) NOT NULL, vendor_id int(10) NOT NULL, service_id int(10) NOT NULL, reservation_date date, status int(10), confirmation_date date, PRIMARY KEY (reservation_id));
CREATE TABLE role (role_id int(10) NOT NULL, name varchar(255), PRIMARY KEY (role_id));
CREATE TABLE scene (scene_id int(10) NOT NULL AUTO_INCREMENT, name varchar(255), description varchar(255), date_created date, date_modified date, user_id int(10) NOT NULL, PRIMARY KEY (scene_id));
CREATE TABLE scene_asset (scene_asset int(10) NOT NULL AUTO_INCREMENT, scene_id int(10) NOT NULL, asset_id int(10) NOT NULL, position int(10), rotation int(10), scale int(10), date_added int(10), PRIMARY KEY (scene_asset));
CREATE TABLE task (task_id int(10) NOT NULL AUTO_INCREMENT, task_name int(10), description varchar(255), status int(10), creation_date date, update_date date, due_date date, priority int(10), event_id int(10) NOT NULL, PRIMARY KEY (task_id));
CREATE TABLE task_progress (progress_id int(10) NOT NULL AUTO_INCREMENT, task_id int(10) NOT NULL, status int(10), change_date date, PRIMARY KEY (progress_id));
CREATE TABLE template_task (template_id int(10) NOT NULL, task_name varchar(255), description varchar(255), priority int(10), PRIMARY KEY (template_id));
CREATE TABLE `User` (user_id int(10) NOT NULL AUTO_INCREMENT, name varchar(255), last_name varchar(255), email varchar(255), phone_number int(10), password varchar(255), address varchar(255), role_id int(10), PRIMARY KEY (user_id));
CREATE TABLE user_preference (preference_id int(10) NOT NULL AUTO_INCREMENT, user_id int(10) NOT NULL, dimensions int(10), grid_dimensions int(10), scene_id int(10) NOT NULL, PRIMARY KEY (preference_id));
CREATE TABLE user_setting (user_setting_id int(10) NOT NULL AUTO_INCREMENT, user_id int(10) NOT NULL, setting_type varchar(255), value varchar(255) NOT NULL, PRIMARY KEY (user_setting_id));
CREATE TABLE vendor (vendor_id int(10) NOT NULL AUTO_INCREMENT, name int(10), category_id int(10) NOT NULL, description int(10), location int(10), rating int(10), registration_date int(10), user_id int(10) NOT NULL, PRIMARY KEY (vendor_id));
CREATE TABLE vendor_category (category_id int(10) NOT NULL AUTO_INCREMENT, category_name varchar(255), description varchar(255), PRIMARY KEY (category_id));
CREATE TABLE vendor_rating_history (vendor_rating_history_id int(10), vendor_id int(10) NOT NULL, rating int(10), rated_date date);
CREATE TABLE vendor_service (vendor_service_id int(10) NOT NULL AUTO_INCREMENT, service_id int(10), vendor_id int(10) NOT NULL, service_name varchar(255), description varchar(255), price decimal(19, 0), availablity varchar(255), PRIMARY KEY (vendor_service_id));
ALTER TABLE reservation ADD CONSTRAINT FKreservatio131084 FOREIGN KEY (vendor_id) REFERENCES vendor (vendor_id);
ALTER TABLE reservation ADD CONSTRAINT FKreservatio703465 FOREIGN KEY (user_id) REFERENCES `User` (user_id);
ALTER TABLE user_preference ADD CONSTRAINT FKuser_prefe410855 FOREIGN KEY (scene_id) REFERENCES scene (scene_id);
ALTER TABLE asset ADD CONSTRAINT FKasset778189 FOREIGN KEY (asset_type_id) REFERENCES asset_type (asset_type_id);
ALTER TABLE scene_asset ADD CONSTRAINT FKscene_asse478035 FOREIGN KEY (asset_id) REFERENCES asset (asset_id);
ALTER TABLE scene_asset ADD CONSTRAINT FKscene_asse915971 FOREIGN KEY (scene_id) REFERENCES scene (scene_id);
ALTER TABLE scene ADD CONSTRAINT FKscene365217 FOREIGN KEY (user_id) REFERENCES `User` (user_id);
ALTER TABLE notification ADD CONSTRAINT FKnotificati613475 FOREIGN KEY (user_id) REFERENCES `User` (user_id);
ALTER TABLE event_template ADD CONSTRAINT FKevent_temp582595 FOREIGN KEY (event_type_id) REFERENCES event_type (event_type_id);
ALTER TABLE template_task ADD CONSTRAINT FKtemplate_t160481 FOREIGN KEY (template_id) REFERENCES event_template (template_id);
ALTER TABLE task_progress ADD CONSTRAINT FKtask_progr505469 FOREIGN KEY (task_id) REFERENCES task (task_id);
ALTER TABLE task ADD CONSTRAINT FKtask682095 FOREIGN KEY (event_id) REFERENCES event (event_id);
ALTER TABLE event ADD CONSTRAINT FKevent594975 FOREIGN KEY (event_type_id) REFERENCES event_type (event_type_id);
ALTER TABLE event_calendar ADD CONSTRAINT FKevent_cale739781 FOREIGN KEY (event_id) REFERENCES event (event_id);
ALTER TABLE message ADD CONSTRAINT FKmessage762015 FOREIGN KEY (chat_id) REFERENCES chat (chat_id);
ALTER TABLE chat ADD CONSTRAINT FKchat567743 FOREIGN KEY (user_id) REFERENCES `User` (user_id);
ALTER TABLE vendor_rating_history ADD CONSTRAINT FKvendor_rat329746 FOREIGN KEY (vendor_id) REFERENCES vendor (vendor_id);
ALTER TABLE vendor ADD CONSTRAINT FKvendor696134 FOREIGN KEY (user_id) REFERENCES `User` (user_id);
ALTER TABLE favorite ADD CONSTRAINT FKfavorite171228 FOREIGN KEY (user_id) REFERENCES `User` (user_id);
ALTER TABLE favorite ADD CONSTRAINT FKfavorite227981 FOREIGN KEY (vendor_id) REFERENCES vendor (vendor_id);
ALTER TABLE reservation ADD CONSTRAINT FKreservatio353952 FOREIGN KEY (service_id) REFERENCES vendor_service (vendor_service_id);
ALTER TABLE vendor ADD CONSTRAINT FKvendor842361 FOREIGN KEY (category_id) REFERENCES vendor_category (category_id);
ALTER TABLE vendor_service ADD CONSTRAINT FKvendor_ser767707 FOREIGN KEY (vendor_id) REFERENCES vendor (vendor_id);
ALTER TABLE role ADD CONSTRAINT FKrole904711 FOREIGN KEY (role_id) REFERENCES `User` (user_id);
ALTER TABLE user_setting ADD CONSTRAINT FKuser_setti995789 FOREIGN KEY (user_id) REFERENCES `User` (user_id);
